### ISSUE TITLE
NFC explanation

### ISSUE THREAD

**Issue by JakobHeller** [Pravinnarola/NFC#2]
Dear Pravin the text for your explanation seems to be a little short so I would suggest you add a little something concerning: 
* How is the coupling enabled (maybe you can make a little picture)
* Frequency
* What is the difference between active and passive readers. (Where is this used)
* Explain an example (like RFID chips for doors)
* What are the advantages of NFC, why is it used at all?

and you should check your **spelling and grammar**

**Comment by franzpl** [comment]
Furthermore, you posted the text in "Projects". However, that is not the right place to publish your work. The project board just helps you to organise your work. 
Please, acquaint yourself with git/github. You will find several tutorials to use git properly. Then, create a **beautiful** "jupyter notebook" and publish it here.

**Comment by Pravinnarola** [comment]
Dear Sir 
Thank you for suggestion and right now i am try to getting familiar with Github and jupyter notebook.i am trying today my self and still i will have problem, then tomorrow i will  come to you. is it ok for you ?

**Comment by franzpl** [comment]
Hi Pravin,


yes, it is ok for us. When do you want to meet us ?


Regards,

Franz

________________________________
Von: Pravinnarola <notifications@github.com>
Gesendet: Montag, 14. Mai 2018 16:56:53
An: Pravinnarola/NFC
Cc: Franz Veit Plocksties; Comment
Betreff: Re: [Pravinnarola/NFC] NFC explanation (#2)


Dear Sir
Thank you for suggestion and right now i am try to getting familiar with Github and jupyter notebook.i am trying today my self and still i will have problem, then tomorrow i will come to you. is it ok for you ?

**Comment by Pravinnarola** [comment]
Dear sir,
i will meet on Wednesday . I think ,i need to spend more time on jupyter notebook , before i will come to you.Thank you .
